name 'wrapper'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures wrapper'
long_description 'Installs/Configures wrapper'
version '0.1.0'
