# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5333fca55db6f8d7c7480ef523508e090fdefa08cc9918d46062cfbc66d4d1b7dc2e9d4662e03c9fc9dc7842e4c6b43f4f3931033c694029024d52485ac16e49

test:
  secret_key_base: 3a2c4329d7707485ae4b78b07c15dfd759f4b3e7017cd54f5dde51a5379936a50d4200c585f085c3578f731cf5f369495be872b5af979649154214661f28bf7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
