source 'https://api.berkshelf.com'

cookbook 'git'
cookbook 'build-essential'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.8.0'
cookbook 'ruby_build'
cookbook 'nodejs'
cookbook 'vim'
